// lib/times.ts

export type TimeConfig = {
  slug: string;
  nome: string;
  nomeOficialAPI: string;
  idAPI?: number;
  esporte: 'futebol' | 'nfl' | 'nba' | 'f1';
  variacoesNome: string[];
  competicaoCodigo: string;
  competicaoNome: string;
  divisaoNFL?: string;
  conferenciaNBA?: 'Eastern Conference' | 'Western Conference';
  // 🏎️ Atributos exclusivos para Fórmula 1
  pilotos?: string[];
  sede?: string;
  fundacao?: string;
  motor?: string;
  chefeEquipe?: string;
  titulosConstrutores?: number;
  titulosPilotos?: number;
  biografia?: string;
  corFundoLogo?: string; // 🎯 Fundo customizado do quadradinho do logo
  // Arquivos de cache (Futebol)
  arquivoStandings?: string;
  arquivoMatches?: string;
  escudo: string;
  corPrimaria: string;
};

// 🇧🇷 Dicionário de Nomes Amigáveis para Clubes Brasileiros
export const nomesTimesBrasil: Record<string, string> = {
  "CA Mineiro": "Atlético-MG",
  "Mineiro": "Atlético-MG",
  "CA Paranaense": "Athletico-PR",
  "Paranaense": "Athletico-PR",
  "CR Flamengo": "Flamengo",
  "SE Palmeiras": "Palmeiras",
  "SC Corinthians Paulista": "Corinthians",
  "São Paulo FC": "São Paulo",
  "Fluminense FC": "Fluminense",
  "Botafogo FR": "Botafogo",
  "CR Vasco da Gama": "Vasco",
  "Grêmio FBPA": "Grêmio",
  "SC Internacional": "Internacional",
  "Cruzeiro EC": "Cruzeiro",
  "EC Bahia": "Bahia",
  "EC Vitória": "Vitória",
  "Santos FC": "Santos",
  "RB Bragantino": "Bragantino",
  "Red Bull Bragantino": "Bragantino",
  "Mirassol FC": "Mirassol",
  "Coritiba FBC": "Coritiba",
  "Clube do Remo": "Remo",
  "Chapecoense AF": "Chapecoense"
};

export function formatarNomeTime(shortName?: string, fullName?: string): string {
  if (shortName && nomesTimesBrasil[shortName]) return nomesTimesBrasil[shortName];
  if (fullName && nomesTimesBrasil[fullName]) return nomesTimesBrasil[fullName];
  return shortName || fullName || 'Time';
}

export const timesConfig: Record<string, TimeConfig> = {

  // ==========================================
  // 🏎️ FÓRMULA 1 (11 EQUIPES OFICIAIS - 2026)
  // ==========================================
  "ferrari": {
    slug: "ferrari",
    nome: "Ferrari",
    nomeOficialAPI: "Ferrari",
    esporte: "f1",
    variacoesNome: ["Ferrari", "Scuderia Ferrari"],
    competicaoCodigo: "F1",
    competicaoNome: "Fórmula 1",
    pilotos: ["Charles Leclerc", "Lewis Hamilton"],
    sede: "Maranello, Itália",
    fundacao: "1929 (Estreia F1 em 1950)",
    motor: "Ferrari",
    chefeEquipe: "Frédéric Vasseur",
    titulosConstrutores: 16,
    titulosPilotos: 15,
    biografia: "A equipe mais icônica e vitoriosa da história da Fórmula 1. Presente em todas as temporadas desde 1950, a Scuderia conta com a histórica dupla Charles Leclerc e Lewis Hamilton.",
    escudo: "https://r2.thesportsdb.com/images/media/team/badge/rxwsqv1420417429.png",
    corPrimaria: "border-red-600 bg-red-50",
    corFundoLogo: "bg-white border-slate-200",
  },
  "mclaren": {
    slug: "mclaren",
    nome: "McLaren",
    nomeOficialAPI: "McLaren",
    esporte: "f1",
    variacoesNome: ["McLaren", "McLaren F1 Team"],
    competicaoCodigo: "F1",
    competicaoNome: "Fórmula 1",
    pilotos: ["Lando Norris", "Oscar Piastri"],
    sede: "Woking, Reino Unido",
    fundacao: "1963",
    motor: "Mercedes",
    chefeEquipe: "Andrea Stella",
    titulosConstrutores: 8,
    titulosPilotos: 12,
    biografia: "Fundada por Bruce McLaren e consagrada pelas lendas Ayrton Senna e Alain Prost, a equipe britânica vive fase de vitórias na era moderna com Lando Norris e Oscar Piastri.",
    escudo: "https://r2.thesportsdb.com/images/media/team/badge/kzqi7v1743602056.png",
    corPrimaria: "border-amber-500 bg-amber-50",
    corFundoLogo: "bg-white border-slate-200"
  },
  "red-bull": {
    slug: "red-bull",
    nome: "Red Bull",
    nomeOficialAPI: "Red Bull",
    esporte: "f1",
    variacoesNome: ["Red Bull", "Red Bull Racing", "RBR"],
    competicaoCodigo: "F1",
    competicaoNome: "Fórmula 1",
    pilotos: ["Max Verstappen", "Isack Hadjar"],
    sede: "Milton Keynes, Reino Unido",
    fundacao: "2005",
    motor: "Red Bull Ford",
    chefeEquipe: "Christian Horner",
    titulosConstrutores: 6,
    titulosPilotos: 7,
    biografia: "Dominante na era moderna da F1, a equipe austríaca conquistou múltiplos títulos mundiais com Sebastian Vettel e Max Verstappen sob liderança técnica de ponta.",
    escudo: "https://r2.thesportsdb.com/images/media/team/badge/nhlev81679826274.png",
    corPrimaria: "border-blue-900 bg-blue-50",
    corFundoLogo: "bg-slate-950 border-slate-800"
  },
  "mercedes": {
    slug: "mercedes",
    nome: "Mercedes",
    nomeOficialAPI: "Mercedes",
    esporte: "f1",
    variacoesNome: ["Mercedes", "Mercedes-AMG", "Mercedes F1"],
    competicaoCodigo: "F1",
    competicaoNome: "Fórmula 1",
    pilotos: ["George Russell", "Kimi Antonelli"],
    sede: "Brackley, Reino Unido",
    fundacao: "1954 (Retorno em 2010)",
    motor: "Mercedes",
    chefeEquipe: "Toto Wolff",
    titulosConstrutores: 8,
    titulosPilotos: 9,
    biografia: "As 'Flechas de Prata' protagonizaram o maior domínio da história da Fórmula 1 na era híbrida (2014-2020), conquistando 8 títulos mundiais de construtores consecutivos.",
    escudo: "https://r2.thesportsdb.com/images/media/team/badge/6caw0r1744037679.png",
    corPrimaria: "border-teal-500 bg-teal-50",
    corFundoLogo: "bg-white border-slate-200"
  },
  "aston-martin": {
    slug: "aston-martin",
    nome: "Aston Martin",
    nomeOficialAPI: "Aston Martin",
    esporte: "f1",
    variacoesNome: ["Aston Martin", "Aston Martin F1"],
    competicaoCodigo: "F1",
    competicaoNome: "Fórmula 1",
    pilotos: ["Fernando Alonso", "Lance Stroll"],
    sede: "Silverstone, Reino Unido",
    fundacao: "2021",
    motor: "Honda",
    chefeEquipe: "Mike Krack",
    titulosConstrutores: 0,
    titulosPilotos: 0,
    biografia: "A tradicional montadora de luxo britânica conta com instalações ultratecnológicas em Silverstone, motores oficiais Honda e a liderança do bicampeão mundial Fernando Alonso.",
    escudo: "https://r2.thesportsdb.com/images/media/team/badge/ez5rlk1740774066.png",
    corPrimaria: "border-emerald-800 bg-emerald-50",
    corFundoLogo: "bg-slate-950 border-slate-800"
  },
  "alpine": {
    slug: "alpine",
    nome: "Alpine",
    nomeOficialAPI: "Alpine",
    esporte: "f1",
    variacoesNome: ["Alpine", "Alpine F1", "Renault"],
    competicaoCodigo: "F1",
    competicaoNome: "Fórmula 1",
    pilotos: ["Pierre Gasly", "Franco Colapinto"],
    sede: "Enstone, Reino Unido",
    fundacao: "1981 (Antiga Benetton / Renault)",
    motor: "Mercedes",
    chefeEquipe: "Oliver Oakes",
    titulosConstrutores: 2,
    titulosPilotos: 2,
    biografia: "Equipe oficial do Grupo Renault, a base de Enstone carrega no currículo os títulos mundiais de Michael Schumacher nos anos 90 e de Fernando Alonso em 2005 e 2006.",
    escudo: "https://r2.thesportsdb.com/images/media/team/badge/ozhoj31740774899.png",
    corPrimaria: "border-blue-600 bg-pink-50",
    corFundoLogo: "bg-slate-950 border-slate-800"
  },
  "williams": {
    slug: "williams",
    nome: "Williams",
    nomeOficialAPI: "Williams",
    esporte: "f1",
    variacoesNome: ["Williams", "Williams Racing"],
    competicaoCodigo: "F1",
    competicaoNome: "Fórmula 1",
    pilotos: ["Carlos Sainz", "Alexander Albon"],
    sede: "Grove, Reino Unido",
    fundacao: "1977",
    motor: "Mercedes",
    chefeEquipe: "James Vowles",
    titulosConstrutores: 9,
    titulosPilotos: 7,
    biografia: "Uma das garagens mais vitoriosas e históricas do automobilismo, com títulos ao lado de Ayrton Senna e Nelson Piquet. Hoje vive grande momento com a forte dupla Carlos Sainz e Alex Albon.",
    escudo: "https://r2.thesportsdb.com/images/media/team/badge/fp1cil1740776050.png",
    corPrimaria: "border-blue-800 bg-blue-50",
    corFundoLogo: "bg-slate-950 border-slate-800"
  },
  "haas": {
    slug: "haas",
    nome: "Haas",
    nomeOficialAPI: "Haas",
    esporte: "f1",
    variacoesNome: ["Haas", "Haas F1 Team"],
    competicaoCodigo: "F1",
    competicaoNome: "Fórmula 1",
    pilotos: ["Esteban Ocon", "Oliver Bearman"],
    sede: "Kannapolis, Estados Unidos",
    fundacao: "2016",
    motor: "Ferrari",
    chefeEquipe: "Ayao Komatsu",
    titulosConstrutores: 0,
    titulosPilotos: 0,
    biografia: "Equipe norte-americana criada por Gene Haas, aposta em modelo de alta eficiência com suporte técnico da Ferrari e uma competitiva dupla de pilotos com Esteban Ocon e Oliver Bearman.",
    escudo: "https://r2.thesportsdb.com/images/media/team/badge/9yp3s51740773680.png",
    corPrimaria: "border-red-600 bg-gray-100",
    corFundoLogo: "bg-white border-slate-200"
  },
  "audi": {
    slug: "audi",
    nome: "Audi F1 Team",
    nomeOficialAPI: "Audi",
    esporte: "f1",
    variacoesNome: ["Audi", "Audi F1", "Sauber", "Audi Revolut"],
    competicaoCodigo: "F1",
    competicaoNome: "Fórmula 1",
    pilotos: ["Gabriel Bortoleto", "Nico Hülkenberg"],
    sede: "Neuburg, Alemanha & Hinwil, Suíça",
    fundacao: "2026 (Entrada oficial de fábrica)",
    motor: "Audi",
    chefeEquipe: "Mattia Binotto",
    titulosConstrutores: 0,
    titulosPilotos: 0,
    biografia: "A gigante montadora alemã entra oficialmente como equipe de fábrica e motor próprio na Fórmula 1! Com sedes na Alemanha e na Suíça, marca o retorno do Brasil ao grid titular com o campeão de base Gabriel Bortoleto.",
    escudo: "https://upload.wikimedia.org/wikipedia/commons/9/92/Audi-Logo_2016.svg",
    corPrimaria: "border-neutral-900 bg-neutral-100",
    corFundoLogo: "bg-white border-slate-200"
  },
  "racing-bulls": {
    slug: "racing-bulls",
    nome: "Racing Bulls",
    nomeOficialAPI: "Racing Bulls",
    esporte: "f1",
    variacoesNome: ["Racing Bulls", "RB", "VCARB", "Toro Rosso"],
    competicaoCodigo: "F1",
    competicaoNome: "Fórmula 1",
    pilotos: ["Liam Lawson", "Arvid Lindblad"],
    sede: "Faenza, Itália",
    fundacao: "2006 (Antiga Minardi)",
    motor: "Red Bull Ford",
    chefeEquipe: "Laurent Mekies",
    titulosConstrutores: 0,
    titulosPilotos: 0,
    biografia: "A equipe italiana sediada em Faenza é famosa por desenvolver campeões mundiais como Sebastian Vettel e Max Verstappen, contando com a veloz dupla Yuki Tsunoda e Liam Lawson.",
    escudo: "https://logos-world.net/wp-content/uploads/2021/03/Aston-Martin-Logo.png",
    corPrimaria: "border-blue-700 bg-blue-50",
    corFundoLogo: "bg-white border-slate-200"
  },
  "cadillac": {
    slug: "cadillac",
    nome: "Cadillac",
    nomeOficialAPI: "Cadillac",
    esporte: "f1",
    variacoesNome: ["Cadillac", "Cadillac F1", "GM F1"],
    competicaoCodigo: "F1",
    competicaoNome: "Fórmula 1",
    pilotos: ["Sergio Pérez", "Valtteri Bottas"],
    sede: "Silverstone, Reino Unido & Indiana, EUA",
    fundacao: "2026",
    motor: "Ferrari",
    chefeEquipe: "Graeme Lowdon",
    titulosConstrutores: 0,
    titulosPilotos: 0,
    biografia: "A 11ª equipe oficial da Fórmula 1! Projeto de peso da General Motors com a marca de luxo Cadillac, estreando com motores Ferrari e a experiente dupla de vencedores de GP Sergio Pérez e Valtteri Bottas.",
    escudo: "https://upload.wikimedia.org/wikipedia/commons/d/d8/Cadillac_Formula_1_Team_logo.png",
    corPrimaria: "border-neutral-800 bg-neutral-100",
    corFundoLogo: "bg-white border-slate-200"
  },

  // ==========================================
  // ⚽ FUTEBOL BRASILEIRO (SÉRIE A)
  // ==========================================
  "flamengo": {
    slug: "flamengo",
    nome: "Flamengo",
    nomeOficialAPI: "CR Flamengo",
    idAPI: 1783,
    esporte: "futebol",
    variacoesNome: ["Flamengo", "CR Flamengo", "Flamengo-RJ"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1783.png",
    corPrimaria: "border-red-600 bg-red-50"
  },
  "palmeiras": {
    slug: "palmeiras",
    nome: "Palmeiras",
    nomeOficialAPI: "SE Palmeiras",
    idAPI: 1769,
    esporte: "futebol",
    variacoesNome: ["Palmeiras", "SE Palmeiras"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1769.png",
    corPrimaria: "border-emerald-600 bg-emerald-50"
  },
  "corinthians": {
    slug: "corinthians",
    nome: "Corinthians",
    nomeOficialAPI: "SC Corinthians Paulista",
    idAPI: 1779,
    esporte: "futebol",
    variacoesNome: ["Corinthians", "SC Corinthians Paulista"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1779.png",
    corPrimaria: "border-gray-900 bg-gray-100"
  },
  "sao-paulo": {
    slug: "sao-paulo",
    nome: "São Paulo",
    nomeOficialAPI: "São Paulo FC",
    idAPI: 1776,
    esporte: "futebol",
    variacoesNome: ["São Paulo", "Sao Paulo", "São Paulo FC"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1776.png",
    corPrimaria: "border-red-700 bg-red-50"
  },
  "santos": {
    slug: "santos",
    nome: "Santos",
    nomeOficialAPI: "Santos FC",
    idAPI: 6685,
    esporte: "futebol",
    variacoesNome: ["Santos", "Santos FC"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/6685.png",
    corPrimaria: "border-gray-800 bg-gray-50"
  },
  "vasco": {
    slug: "vasco",
    nome: "Vasco da Gama",
    nomeOficialAPI: "CR Vasco da Gama",
    idAPI: 1780,
    esporte: "futebol",
    variacoesNome: ["Vasco", "Vasco da Gama", "CR Vasco da Gama"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1780.png",
    corPrimaria: "border-gray-900 bg-gray-100"
  },
  "botafogo": {
    slug: "botafogo",
    nome: "Botafogo",
    nomeOficialAPI: "Botafogo FR",
    idAPI: 1770,
    esporte: "futebol",
    variacoesNome: ["Botafogo", "Botafogo FR", "Botafogo-RJ"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1770.png",
    corPrimaria: "border-gray-900 bg-gray-100"
  },
  "fluminense": {
    slug: "fluminense",
    nome: "Fluminense",
    nomeOficialAPI: "Fluminense FC",
    idAPI: 1765,
    esporte: "futebol",
    variacoesNome: ["Fluminense", "Fluminense FC"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1765.png",
    corPrimaria: "border-red-800 bg-green-50"
  },
  "gremio": {
    slug: "gremio",
    nome: "Grêmio",
    nomeOficialAPI: "Grêmio FBPA",
    idAPI: 1767,
    esporte: "futebol",
    variacoesNome: ["Grêmio", "Gremio", "Grêmio FBPA"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1767.png",
    corPrimaria: "border-sky-600 bg-sky-50"
  },
  "internacional": {
    slug: "internacional",
    nome: "Internacional",
    nomeOficialAPI: "SC Internacional",
    idAPI: 6684,
    esporte: "futebol",
    variacoesNome: ["Internacional", "Inter", "SC Internacional"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/6684.png",
    corPrimaria: "border-red-600 bg-red-50"
  },
  "cruzeiro": {
    slug: "cruzeiro",
    nome: "Cruzeiro",
    nomeOficialAPI: "Cruzeiro EC",
    idAPI: 1771,
    esporte: "futebol",
    variacoesNome: ["Cruzeiro", "Cruzeiro EC"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1771.png",
    corPrimaria: "border-blue-600 bg-blue-50"
  },
  "atletico-mineiro": {
    slug: "atletico-mineiro",
    nome: "Atlético-MG",
    nomeOficialAPI: "CA Mineiro",
    idAPI: 1766,
    esporte: "futebol",
    variacoesNome: ["Atlético-MG", "Atletico-MG", "Atlético Mineiro", "CA Mineiro"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1766.png",
    corPrimaria: "border-gray-900 bg-gray-50"
  },
  "bahia": {
    slug: "bahia",
    nome: "Bahia",
    nomeOficialAPI: "EC Bahia",
    idAPI: 1777,
    esporte: "futebol",
    variacoesNome: ["Bahia", "EC Bahia"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1777.png",
    corPrimaria: "border-blue-600 bg-red-50"
  },
  "athletico-pr": {
    slug: "athletico-pr",
    nome: "Athletico-PR",
    nomeOficialAPI: "CA Paranaense",
    idAPI: 1768,
    esporte: "futebol",
    variacoesNome: ["Athletico-PR", "Athletico PR", "CA Paranaense", "Athletico"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/1768.png",
    corPrimaria: "border-red-600 bg-red-50"
  },
  "red-bull-bragantino": {
    slug: "red-bull-bragantino",
    nome: "RB Bragantino",
    nomeOficialAPI: "RB Bragantino",
    idAPI: 4286,
    esporte: "futebol",
    variacoesNome: ["RB Bragantino", "Bragantino", "Red Bull Bragantino"],
    competicaoCodigo: "BSA",
    competicaoNome: "Brasileirão Série A",
    arquivoStandings: "brasileirao-standings.json",
    arquivoMatches: "brasileirao-matches.json",
    escudo: "https://crests.football-data.org/4286.png",
    corPrimaria: "border-red-600 bg-gray-50"
  },

  // ==========================================
  // ⚽ GIGANTES DA EUROPA
  // ==========================================
  "real-madrid": {
    slug: "real-madrid",
    nome: "Real Madrid",
    nomeOficialAPI: "Real Madrid CF",
    idAPI: 86,
    esporte: "futebol",
    variacoesNome: ["Real Madrid", "Real Madrid CF"],
    competicaoCodigo: "PD",
    competicaoNome: "La Liga",
    arquivoStandings: "la-liga-standings.json",
    arquivoMatches: "la-liga-matches.json",
    escudo: "https://crests.football-data.org/86.png",
    corPrimaria: "border-yellow-500 bg-yellow-50"
  },
  "barcelona": {
    slug: "barcelona",
    nome: "Barcelona",
    nomeOficialAPI: "FC Barcelona",
    idAPI: 81,
    esporte: "futebol",
    variacoesNome: ["Barcelona", "FC Barcelona"],
    competicaoCodigo: "PD",
    competicaoNome: "La Liga",
    arquivoStandings: "la-liga-standings.json",
    arquivoMatches: "la-liga-matches.json",
    escudo: "https://crests.football-data.org/81.png",
    corPrimaria: "border-blue-700 bg-red-50"
  },
  "manchester-city": {
    slug: "manchester-city",
    nome: "Manchester City",
    nomeOficialAPI: "Manchester City FC",
    idAPI: 65,
    esporte: "futebol",
    variacoesNome: ["Manchester City", "Man City", "City"],
    competicaoCodigo: "PL",
    competicaoNome: "Premier League",
    arquivoStandings: "premier-league-standings.json",
    arquivoMatches: "premier-league-matches.json",
    escudo: "https://crests.football-data.org/65.png",
    corPrimaria: "border-sky-500 bg-sky-50"
  },
  "liverpool": {
    slug: "liverpool",
    nome: "Liverpool",
    nomeOficialAPI: "Liverpool FC",
    idAPI: 64,
    esporte: "futebol",
    variacoesNome: ["Liverpool", "Liverpool FC"],
    competicaoCodigo: "PL",
    competicaoNome: "Premier League",
    arquivoStandings: "premier-league-standings.json",
    arquivoMatches: "premier-league-matches.json",
    escudo: "https://crests.football-data.org/64.png",
    corPrimaria: "border-red-600 bg-red-50"
  },
  "arsenal": {
    slug: "arsenal",
    nome: "Arsenal",
    nomeOficialAPI: "Arsenal FC",
    idAPI: 57,
    esporte: "futebol",
    variacoesNome: ["Arsenal", "Arsenal FC"],
    competicaoCodigo: "PL",
    competicaoNome: "Premier League",
    arquivoStandings: "premier-league-standings.json",
    arquivoMatches: "premier-league-matches.json",
    escudo: "https://crests.football-data.org/57.png",
    corPrimaria: "border-red-600 bg-red-50"
  },

  // ==========================================
  // 🏀 FRANQUIAS DA NBA
  // ==========================================
  "los-angeles-lakers": {
    slug: "los-angeles-lakers",
    nome: "Los Angeles Lakers",
    nomeOficialAPI: "Los Angeles Lakers",
    idAPI: 13,
    esporte: "nba",
    variacoesNome: ["Los Angeles Lakers", "Lakers", "LA Lakers"],
    competicaoCodigo: "NBA",
    competicaoNome: "NBA",
    conferenciaNBA: "Western Conference",
    escudo: "https://a.espncdn.com/i/teamlogos/nba/500/lal.png",
    corPrimaria: "border-purple-800 bg-yellow-50"
  },
  "boston-celtics": {
    slug: "boston-celtics",
    nome: "Boston Celtics",
    nomeOficialAPI: "Boston Celtics",
    idAPI: 2,
    esporte: "nba",
    variacoesNome: ["Boston Celtics", "Celtics"],
    competicaoCodigo: "NBA",
    competicaoNome: "NBA",
    conferenciaNBA: "Eastern Conference",
    escudo: "https://a.espncdn.com/i/teamlogos/nba/500/bos.png",
    corPrimaria: "border-emerald-700 bg-emerald-50"
  },
  "golden-state-warriors": {
    slug: "golden-state-warriors",
    nome: "Golden State Warriors",
    nomeOficialAPI: "Golden State Warriors",
    idAPI: 9,
    esporte: "nba",
    variacoesNome: ["Golden State Warriors", "Warriors", "GS Warriors"],
    competicaoCodigo: "NBA",
    competicaoNome: "NBA",
    conferenciaNBA: "Western Conference",
    escudo: "https://a.espncdn.com/i/teamlogos/nba/500/gsw.png",
    corPrimaria: "border-blue-700 bg-yellow-50"
  },
  "chicago-bulls": {
    slug: "chicago-bulls",
    nome: "Chicago Bulls",
    nomeOficialAPI: "Chicago Bulls",
    idAPI: 4,
    esporte: "nba",
    variacoesNome: ["Chicago Bulls", "Bulls"],
    competicaoCodigo: "NBA",
    competicaoNome: "NBA",
    conferenciaNBA: "Eastern Conference",
    escudo: "https://a.espncdn.com/i/teamlogos/nba/500/chi.png",
    corPrimaria: "border-red-600 bg-red-50"
  },
  "miami-heat": {
    slug: "miami-heat",
    nome: "Miami Heat",
    nomeOficialAPI: "Miami Heat",
    idAPI: 14,
    esporte: "nba",
    variacoesNome: ["Miami Heat", "Heat"],
    competicaoCodigo: "NBA",
    competicaoNome: "NBA",
    conferenciaNBA: "Eastern Conference",
    escudo: "https://a.espncdn.com/i/teamlogos/nba/500/mia.png",
    corPrimaria: "border-red-800 bg-red-50"
  },
  "new-york-knicks": {
    slug: "new-york-knicks",
    nome: "New York Knicks",
    nomeOficialAPI: "New York Knicks",
    idAPI: 18,
    esporte: "nba",
    variacoesNome: ["New York Knicks", "Knicks", "NY Knicks"],
    competicaoCodigo: "NBA",
    competicaoNome: "NBA",
    conferenciaNBA: "Eastern Conference",
    escudo: "https://a.espncdn.com/i/teamlogos/nba/500/nyk.png",
    corPrimaria: "border-blue-600 bg-orange-50"
  },
  "denver-nuggets": {
    slug: "denver-nuggets",
    nome: "Denver Nuggets",
    nomeOficialAPI: "Denver Nuggets",
    idAPI: 7,
    esporte: "nba",
    variacoesNome: ["Denver Nuggets", "Nuggets"],
    competicaoCodigo: "NBA",
    competicaoNome: "NBA",
    conferenciaNBA: "Western Conference",
    escudo: "https://a.espncdn.com/i/teamlogos/nba/500/den.png",
    corPrimaria: "border-blue-900 bg-yellow-50"
  },
  "phoenix-suns": {
    slug: "phoenix-suns",
    nome: "Phoenix Suns",
    nomeOficialAPI: "Phoenix Suns",
    idAPI: 21,
    esporte: "nba",
    variacoesNome: ["Phoenix Suns", "Suns"],
    competicaoCodigo: "NBA",
    competicaoNome: "NBA",
    conferenciaNBA: "Western Conference",
    escudo: "https://a.espncdn.com/i/teamlogos/nba/500/phx.png",
    corPrimaria: "border-orange-600 bg-purple-50"
  },
  "dallas-mavericks": {
    slug: "dallas-mavericks",
    nome: "Dallas Mavericks",
    nomeOficialAPI: "Dallas Mavericks",
    idAPI: 6,
    esporte: "nba",
    variacoesNome: ["Dallas Mavericks", "Mavs"],
    competicaoCodigo: "NBA",
    competicaoNome: "NBA",
    conferenciaNBA: "Western Conference",
    escudo: "https://a.espncdn.com/i/teamlogos/nba/500/dal.png",
    corPrimaria: "border-blue-700 bg-blue-50"
  },
  "milwaukee-bucks": {
    slug: "milwaukee-bucks",
    nome: "Milwaukee Bucks",
    nomeOficialAPI: "Milwaukee Bucks",
    idAPI: 15,
    esporte: "nba",
    variacoesNome: ["Milwaukee Bucks", "Bucks"],
    competicaoCodigo: "NBA",
    competicaoNome: "NBA",
    conferenciaNBA: "Eastern Conference",
    escudo: "https://a.espncdn.com/i/teamlogos/nba/500/mil.png",
    corPrimaria: "border-emerald-800 bg-emerald-50"
  },

  // ==========================================
  // 🏈 FRANQUIAS DA NFL
  // ==========================================
  "kansas-city-chiefs": {
    slug: "kansas-city-chiefs",
    nome: "Kansas City Chiefs",
    nomeOficialAPI: "Kansas City Chiefs",
    esporte: "nfl",
    variacoesNome: ["Kansas City Chiefs", "Chiefs"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC West",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/kc.png",
    corPrimaria: "border-red-600 bg-red-50"
  },
  "philadelphia-eagles": {
    slug: "philadelphia-eagles",
    nome: "Philadelphia Eagles",
    nomeOficialAPI: "Philadelphia Eagles",
    esporte: "nfl",
    variacoesNome: ["Philadelphia Eagles", "Eagles"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC East",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/phi.png",
    corPrimaria: "border-emerald-800 bg-emerald-50"
  },
  "san-francisco-49ers": {
    slug: "san-francisco-49ers",
    nome: "San Francisco 49ers",
    nomeOficialAPI: "San Francisco 49ers",
    esporte: "nfl",
    variacoesNome: ["San Francisco 49ers", "49ers", "San Francisco"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC West",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/sf.png",
    corPrimaria: "border-red-700 bg-yellow-50"
  },
  "dallas-cowboys": {
    slug: "dallas-cowboys",
    nome: "Dallas Cowboys",
    nomeOficialAPI: "Dallas Cowboys",
    esporte: "nfl",
    variacoesNome: ["Dallas Cowboys", "Cowboys"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC East",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/dal.png",
    corPrimaria: "border-blue-900 bg-blue-50"
  },
  "baltimore-ravens": {
    slug: "baltimore-ravens",
    nome: "Baltimore Ravens",
    nomeOficialAPI: "Baltimore Ravens",
    esporte: "nfl",
    variacoesNome: ["Baltimore Ravens", "Ravens"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC North",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/bal.png",
    corPrimaria: "border-purple-900 bg-purple-50"
  },
  "buffalo-bills": {
    slug: "buffalo-bills",
    nome: "Buffalo Bills",
    nomeOficialAPI: "Buffalo Bills",
    esporte: "nfl",
    variacoesNome: ["Buffalo Bills", "Bills"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC East",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/buf.png",
    corPrimaria: "border-blue-700 bg-blue-50"
  },
  "green-bay-packers": {
    slug: "green-bay-packers",
    nome: "Green Bay Packers",
    nomeOficialAPI: "Green Bay Packers",
    esporte: "nfl",
    variacoesNome: ["Green Bay Packers", "Packers"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC North",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/gb.png",
    corPrimaria: "border-green-800 bg-yellow-50"
  },
  "detroit-lions": {
    slug: "detroit-lions",
    nome: "Detroit Lions",
    nomeOficialAPI: "Detroit Lions",
    esporte: "nfl",
    variacoesNome: ["Detroit Lions", "Lions"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC North",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/det.png",
    corPrimaria: "border-sky-600 bg-blue-50"
  },
  "miami-dolphins": {
    slug: "miami-dolphins",
    nome: "Miami Dolphins",
    nomeOficialAPI: "Miami Dolphins",
    esporte: "nfl",
    variacoesNome: ["Miami Dolphins", "Dolphins"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC East",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/mia.png",
    corPrimaria: "border-teal-600 bg-orange-50"
  },
  "new-england-patriots": {
    slug: "new-england-patriots",
    nome: "New England Patriots",
    nomeOficialAPI: "New England Patriots",
    esporte: "nfl",
    variacoesNome: ["New England Patriots", "Patriots"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC East",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/ne.png",
    corPrimaria: "border-blue-950 bg-red-50"
  },
  "new-york-jets": {
    slug: "new-york-jets",
    nome: "New York Jets",
    nomeOficialAPI: "New York Jets",
    esporte: "nfl",
    variacoesNome: ["New York Jets", "Jets"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC East",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png",
    corPrimaria: "border-emerald-800 bg-emerald-50"
  },
  "cincinnati-bengals": {
    slug: "cincinnati-bengals",
    nome: "Cincinnati Bengals",
    nomeOficialAPI: "Cincinnati Bengals",
    esporte: "nfl",
    variacoesNome: ["Cincinnati Bengals", "Bengals"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC North",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/cin.png",
    corPrimaria: "border-orange-600 bg-gray-50"
  },
  "cleveland-browns": {
    slug: "cleveland-browns",
    nome: "Cleveland Browns",
    nomeOficialAPI: "Cleveland Browns",
    esporte: "nfl",
    variacoesNome: ["Cleveland Browns", "Browns"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC North",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/cle.png",
    corPrimaria: "border-orange-700 bg-orange-50"
  },
  "pittsburgh-steelers": {
    slug: "pittsburgh-steelers",
    nome: "Pittsburgh Steelers",
    nomeOficialAPI: "Pittsburgh Steelers",
    esporte: "nfl",
    variacoesNome: ["Pittsburgh Steelers", "Steelers"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC North",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/pit.png",
    corPrimaria: "border-yellow-500 bg-gray-100"
  },
  "houston-texans": {
    slug: "houston-texans",
    nome: "Houston Texans",
    nomeOficialAPI: "Houston Texans",
    esporte: "nfl",
    variacoesNome: ["Houston Texans", "Texans"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC South",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/hou.png",
    corPrimaria: "border-blue-900 bg-red-50"
  },
  "indianapolis-colts": {
    slug: "indianapolis-colts",
    nome: "Indianapolis Colts",
    nomeOficialAPI: "Indianapolis Colts",
    esporte: "nfl",
    variacoesNome: ["Indianapolis Colts", "Colts"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC South",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/ind.png",
    corPrimaria: "border-blue-700 bg-blue-50"
  },
  "jacksonville-jaguars": {
    slug: "jacksonville-jaguars",
    nome: "Jacksonville Jaguars",
    nomeOficialAPI: "Jacksonville Jaguars",
    esporte: "nfl",
    variacoesNome: ["Jacksonville Jaguars", "Jaguars"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC South",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/jax.png",
    corPrimaria: "border-teal-700 bg-amber-50"
  },
  "tennessee-titans": {
    slug: "tennessee-titans",
    nome: "Tennessee Titans",
    nomeOficialAPI: "Tennessee Titans",
    esporte: "nfl",
    variacoesNome: ["Tennessee Titans", "Titans"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC South",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/ten.png",
    corPrimaria: "border-sky-700 bg-red-50"
  },
  "denver-broncos": {
    slug: "denver-broncos",
    nome: "Denver Broncos",
    nomeOficialAPI: "Denver Broncos",
    esporte: "nfl",
    variacoesNome: ["Denver Broncos", "Broncos"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC West",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/den.png",
    corPrimaria: "border-orange-600 bg-blue-50"
  },
  "las-vegas-raiders": {
    slug: "las-vegas-raiders",
    nome: "Las Vegas Raiders",
    nomeOficialAPI: "Las Vegas Raiders",
    esporte: "nfl",
    variacoesNome: ["Las Vegas Raiders", "Raiders"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC West",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/lv.png",
    corPrimaria: "border-gray-900 bg-gray-100"
  },
  "los-angeles-chargers": {
    slug: "los-angeles-chargers",
    nome: "Los Angeles Chargers",
    nomeOficialAPI: "Los Angeles Chargers",
    esporte: "nfl",
    variacoesNome: ["Los Angeles Chargers", "Chargers"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "AFC West",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/lac.png",
    corPrimaria: "border-sky-500 bg-yellow-50"
  },
  "new-york-giants": {
    slug: "new-york-giants",
    nome: "New York Giants",
    nomeOficialAPI: "New York Giants",
    esporte: "nfl",
    variacoesNome: ["New York Giants", "Giants"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC East",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png",
    corPrimaria: "border-blue-800 bg-red-50"
  },
  "washington-commanders": {
    slug: "washington-commanders",
    nome: "Washington Commanders",
    nomeOficialAPI: "Washington Commanders",
    esporte: "nfl",
    variacoesNome: ["Washington Commanders", "Commanders"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC East",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png",
    corPrimaria: "border-amber-800 bg-amber-50"
  },
  "chicago-bears": {
    slug: "chicago-bears",
    nome: "Chicago Bears",
    nomeOficialAPI: "Chicago Bears",
    esporte: "nfl",
    variacoesNome: ["Chicago Bears", "Bears"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC North",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/chi.png",
    corPrimaria: "border-blue-950 bg-orange-50"
  },
  "minnesota-vikings": {
    slug: "minnesota-vikings",
    nome: "Minnesota Vikings",
    nomeOficialAPI: "Minnesota Vikings",
    esporte: "nfl",
    variacoesNome: ["Minnesota Vikings", "Vikings"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC North",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/min.png",
    corPrimaria: "border-purple-800 bg-yellow-50"
  },
  "atlanta-falcons": {
    slug: "atlanta-falcons",
    nome: "Atlanta Falcons",
    nomeOficialAPI: "Atlanta Falcons",
    esporte: "nfl",
    variacoesNome: ["Atlanta Falcons", "Falcons"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC South",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/atl.png",
    corPrimaria: "border-red-600 bg-gray-100"
  },
  "carolina-panthers": {
    slug: "carolina-panthers",
    nome: "Carolina Panthers",
    nomeOficialAPI: "Carolina Panthers",
    esporte: "nfl",
    variacoesNome: ["Carolina Panthers", "Panthers"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC South",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/car.png",
    corPrimaria: "border-cyan-600 bg-gray-100"
  },
  "new-orleans-saints": {
    slug: "new-orleans-saints",
    nome: "New Orleans Saints",
    nomeOficialAPI: "New Orleans Saints",
    esporte: "nfl",
    variacoesNome: ["New Orleans Saints", "Saints"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC South",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/no.png",
    corPrimaria: "border-amber-600 bg-gray-100"
  },
  "tampa-bay-buccaneers": {
    slug: "tampa-bay-buccaneers",
    nome: "Tampa Bay Buccaneers",
    nomeOficialAPI: "Tampa Bay Buccaneers",
    esporte: "nfl",
    variacoesNome: ["Tampa Bay Buccaneers", "Buccaneers", "Bucs"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC South",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/tb.png",
    corPrimaria: "border-red-700 bg-gray-100"
  },
  "arizona-cardinals": {
    slug: "arizona-cardinals",
    nome: "Arizona Cardinals",
    nomeOficialAPI: "Arizona Cardinals",
    esporte: "nfl",
    variacoesNome: ["Arizona Cardinals", "Cardinals"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC West",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/ari.png",
    corPrimaria: "border-red-600 bg-yellow-50"
  },
  "los-angeles-rams": {
    slug: "los-angeles-rams",
    nome: "Los Angeles Rams",
    nomeOficialAPI: "Los Angeles Rams",
    esporte: "nfl",
    variacoesNome: ["Los Angeles Rams", "Rams"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC West",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/lar.png",
    corPrimaria: "border-blue-600 bg-yellow-50"
  },
  "seattle-seahawks": {
    slug: "seattle-seahawks",
    nome: "Seattle Seahawks",
    nomeOficialAPI: "Seattle Seahawks",
    esporte: "nfl",
    variacoesNome: ["Seattle Seahawks", "Seahawks"],
    competicaoCodigo: "NFL",
    competicaoNome: "NFL",
    divisaoNFL: "NFC West",
    escudo: "https://a.espncdn.com/i/teamlogos/nfl/500/sea.png",
    corPrimaria: "border-blue-900 bg-emerald-50"
  }
};